In [9]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [29]:
dataframe = pd.read_csv('./Dataset/Dataset.csv', encoding='ISO-8859-1')

In [30]:
dataframe

,Student ID,Student Country,Question ID,Type of Answer,Question Level,Topic,Subtopic,Keywords
0,647,Ireland,77,0,Basic,Statistics,Statistics,Stem and Leaf diagram|Relative frequency|Sampl...
1,41,Portugal,77,1,Basic,Statistics,Statistics,Stem and Leaf diagram|Relative frequency|Sampl...
2,340,Portugal,77,1,Basic,Statistics,Statistics,Stem and Leaf diagram|Relative frequency|Sampl...
3,641,Italy,77,0,Basic,Statistics,Statistics,Stem and Leaf diagram|Relative frequency|Sampl...
4,669,Portugal,77,1,Basic,Statistics,Statistics,Stem and Leaf diagram|Relative frequency|Sampl...
...,...,...,...,...,...,...,...,...
9541,175,Italy,1497,1,Basic,Complex Numbers,Complex Numbers,Imaginary part|Conjugate number|Modulus of a c...
9542,175,Italy,1514,0,Basic,Complex Numbers,Complex Numbers,Operations with complex numbers||||||||||||
9543,175,Italy,1521,0,Basic,Fundamental Mathematics,Algebraic expressions,"| Equations| and Inequalities,Quadratic equati..."
9544,175,Italy,1526,1,Basic,Fundamental Mathematics,Algebraic expressions,"| Equations| and Inequalities,Linear equations..."
9545,175,Italy,1549,0,Basic,Fundamental Mathematics,Algebraic expressions,"| Equations| and Inequalities,Simplify express..."

In [38]:
keywords_expanded = dataframe['Keywords'].str.split('|', expand=True)
keywords_expanded

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,Stem and Leaf diagram,Relative frequency,Sample,Frequency,,,,,,,,,
1,Stem and Leaf diagram,Relative frequency,Sample,Frequency,,,,,,,,,
2,Stem and Leaf diagram,Relative frequency,Sample,Frequency,,,,,,,,,
3,Stem and Leaf diagram,Relative frequency,Sample,Frequency,,,,,,,,,
4,Stem and Leaf diagram,Relative frequency,Sample,Frequency,,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9541,Imaginary part,Conjugate number,Modulus of a complex number,Algebraic form,Real part,Equations involving complex numbers,,,,,,,
9542,Operations with complex numbers,,,,,,,,,,,,
9543,,Equations,"and Inequalities,Quadratic equations",Simplify expressions,Linear equations,,,,,,,,
9544,,Equations,"and Inequalities,Linear equations",Quadratic equations,Simplify expressions,,,,,,,,
9545,,Equations,"and Inequalities,Simplify expressions",Linear equations,Quadratic equations,,,,,,,,

In [41]:
dataframe_keywords = pd.get_dummies(keywords_expanded.stack())
dataframe_keywords

                 Equations   Image and Graphics,Domain  \
0    0   False       False                       False
     1   False       False                       False
     2   False       False                       False
     3   False       False                       False
     4    True       False                       False
...        ...         ...                         ...
9545 8    True       False                       False
     9    True       False                       False
     10   True       False                       False
     11   True       False                       False
     12   True       False                       False

          Image and Graphics,Indeterminate forms  \
0    0                                     False
     1                                     False
     2                                     False
     3                                     False
     4                                     False
...                                          ...
9545 8                                     False
     9                                     False
     10                                    False
     11                                    False
     12                                    False

          Image and Graphics,Planar graph   Integration by parts  \
0    0                              False                  False
     1                              False                  False
     2                              False                  False
     3                              False                  False
     4                              False                  False
...                                   ...                    ...
9545 8                              False                  False
     9                              False                  False
     10                             False                  False
     11                             False                  False
     12                             False                  False

          and Inequalities,Exponential function  \
0    0                                    False
     1                                    False
     2                                    False
     3                                    False
     4                                    False
...                                         ...
9545 8                                    False
     9                                    False
     10                                   False
     11                                   False
     12                                   False

          and Inequalities,Linear equations  \
0    0                                False
     1                                False
     2                                False
     3                                False
     4                                False
...                                     ...
9545 8                                False
     9                                False
     10                               False
     11                               False
     12                               False

          and Inequalities,Logarithmic function  \
0    0                                    False
     1                                    False
     2                                    False
     3                                    False
     4                                    False
...                                         ...
9545 8                                    False
     9                                    False
     10                                   False
     11                                   False
     12                                   False

          and Inequalities,Quadratic equations  ...  Trigonometric rules  \
0    0                                   False  ...                False
     1                                   False  ...                False
     2                                   False  ...                False
     3                                   False  ...                False
     4                                   False  ...                False
...                                        ...  ...                  ...
9545 8                                   False  ...                False
     9                                   False  ...                False
     10                                  False  ...                False
     11                                  False  ...                False
     12                                  False  ...                False

         Trigonometric substitution  Unconstrained optimization  \
0    0                        False                       False
     1                        False                       False
     2                        False                       False
     3                        False                       False
     4                        False                       False
...                             ...                         ...
9545 8                        False                       False
     9                        False                       False
     10                       False                       False
     11                       False                       False
     12                       False                       False

         Undetermined solution of linear system  Union of sets  Variance  \
0    0                                    False          False     False
     1                                    False          False     False
     2                                    False          False     False
     3                                    False          False     False
     4                                    False          False     False
...                                         ...            ...       ...
9545 8                                    False          False     False
     9                                    False          False     False
     10                                   False          False     False
     11                                   False          False     False
     12                                   False          False     False

         Venn diagram  Volume of revolution  x-simple region (type II)  \
0    0          False                 False                      False
     1          False                 False                      False
     2          False                 False                      False
     3          False                 False                      False
     4          False                 False                      False
...               ...                   ...                        ...
9545 8          False                 False                      False
     9          False                 False                      False
     10         False                 False                      False
     11         False                 False                      False
     12         False                 False                      False

         y-simple region (type I)
0    0                      False
     1                      False
     2                      False
     3                      False
     4                      False
...                           ...
9545 8                      False
     9                      False
     10                     False
     11                     False
     12                     False

[124098 rows x 203 columns]

In [42]:
dataframe = pd.concat([dataframe, dataframe_keywords], axis = 1)
dataframe

,Student ID,Student Country,Question ID,Type of Answer,Question Level,Topic,Subtopic,Keywords,combined_keywords,,...,Trigonometric rules,Trigonometric substitution,Unconstrained optimization,Undetermined solution of linear system,Union of sets,Variance,Venn diagram,Volume of revolution,x-simple region (type II),y-simple region (type I)
0,647.0,Ireland,77.0,0.0,Basic,Statistics,Statistics,Stem and Leaf diagram|Relative frequency|Sampl...,647|Ireland|77|0|Basic|Statistics|Statistics|S...,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,41.0,Portugal,77.0,1.0,Basic,Statistics,Statistics,Stem and Leaf diagram|Relative frequency|Sampl...,41|Portugal|77|1|Basic|Statistics|Statistics|S...,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,340.0,Portugal,77.0,1.0,Basic,Statistics,Statistics,Stem and Leaf diagram|Relative frequency|Sampl...,340|Portugal|77|1|Basic|Statistics|Statistics|...,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,641.0,Italy,77.0,0.0,Basic,Statistics,Statistics,Stem and Leaf diagram|Relative frequency|Sampl...,641|Italy|77|0|Basic|Statistics|Statistics|Ste...,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,669.0,Portugal,77.0,1.0,Basic,Statistics,Statistics,Stem and Leaf diagram|Relative frequency|Sampl...,669|Portugal|77|1|Basic|Statistics|Statistics|...,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
"(9545, 8)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,...,False,False,False,False,False,False,False,False,False,False
"(9545, 9)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,...,False,False,False,False,False,False,False,False,False,False
"(9545, 10)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,...,False,False,False,False,False,False,False,False,False,False
"(9545, 11)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,...,False,False,False,False,False,False,False,False,False,False
"(9545, 12)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,...,False,False,False,False,False,False,False,False,False,False